from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Basic(object):
    def setupUi(self, Basic):
        Basic.setObjectName("Basic")
        Basic.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        Basic.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Basic)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Setting = QtWidgets.QFrame(Basic)
        self.Setting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Setting.sizePolicy().hasHeightForWidth())
        self.Setting.setSizePolicy(sizePolicy)
        self.Setting.setMinimumSize(QtCore.QSize(100, 0))
        self.Setting.setMaximumSize(QtCore.QSize(220, 16777215))
        self.Setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Setting.setObjectName("Setting")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoadDataButton = QtWidgets.QPushButton(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LoadDataButton.sizePolicy().hasHeightForWidth()
        )
        self.LoadDataButton.setSizePolicy(sizePolicy)
        self.LoadDataButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.LoadDataButton.setFont(font)
        self.LoadDataButton.setObjectName("LoadDataButton")
        self.verticalLayout_2.addWidget(self.LoadDataButton)
        self.SamplingRateSetting = QtWidgets.QWidget(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SamplingRateSetting.sizePolicy().hasHeightForWidth()
        )
        self.SamplingRateSetting.setSizePolicy(sizePolicy)
        self.SamplingRateSetting.setMinimumSize(QtCore.QSize(0, 40))
        self.SamplingRateSetting.setObjectName("SamplingRateSetting")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SamplingRateSetting)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SamplingRateLabel = QtWidgets.QLabel(self.SamplingRateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SamplingRateLabel.sizePolicy().hasHeightForWidth()
        )
        self.SamplingRateLabel.setSizePolicy(sizePolicy)
        self.SamplingRateLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.SamplingRateLabel.setFont(font)
        self.SamplingRateLabel.setObjectName("SamplingRateLabel")
        self.horizontalLayout_2.addWidget(self.SamplingRateLabel)
        self.SamplingRate = QtWidgets.QLineEdit(self.SamplingRateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SamplingRate.sizePolicy().hasHeightForWidth())
        self.SamplingRate.setSizePolicy(sizePolicy)
        self.SamplingRate.setMinimumSize(QtCore.QSize(0, 20))
        self.SamplingRate.setObjectName("SamplingRate")
        self.horizontalLayout_2.addWidget(self.SamplingRate)
        self.SamplingRateUnit = QtWidgets.QLabel(self.SamplingRateSetting)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(False)
        self.SamplingRateUnit.setFont(font)
        self.SamplingRateUnit.setObjectName("SamplingRateUnit")
        self.horizontalLayout_2.addWidget(self.SamplingRateUnit)
        self.verticalLayout_2.addWidget(
            self.SamplingRateSetting, 0, QtCore.Qt.AlignVCenter
        )
        self.Rotate = QtWidgets.QFrame(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rotate.sizePolicy().hasHeightForWidth())
        self.Rotate.setSizePolicy(sizePolicy)
        self.Rotate.setMinimumSize(QtCore.QSize(0, 100))
        self.Rotate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Rotate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Rotate.setObjectName("Rotate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Rotate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RotateGuttons = QtWidgets.QWidget(self.Rotate)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.RotateGuttons.sizePolicy().hasHeightForWidth()
        )
        self.RotateGuttons.setSizePolicy(sizePolicy)
        self.RotateGuttons.setMinimumSize(QtCore.QSize(0, 40))
        self.RotateGuttons.setObjectName("RotateGuttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.RotateGuttons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ResetButton = QtWidgets.QPushButton(self.RotateGuttons)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setMinimumSize(QtCore.QSize(0, 20))
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout_4.addWidget(self.ResetButton)
        self.ConfirmButton = QtWidgets.QPushButton(self.RotateGuttons)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ConfirmButton.sizePolicy().hasHeightForWidth()
        )
        self.ConfirmButton.setSizePolicy(sizePolicy)
        self.ConfirmButton.setMinimumSize(QtCore.QSize(0, 20))
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.horizontalLayout_4.addWidget(self.ConfirmButton)
        self.gridLayout_2.addWidget(self.RotateGuttons, 0, 1, 1, 1)
        self.RotateLabel = QtWidgets.QLabel(self.Rotate)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotateLabel.sizePolicy().hasHeightForWidth())
        self.RotateLabel.setSizePolicy(sizePolicy)
        self.RotateLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.RotateLabel.setFont(font)
        self.RotateLabel.setObjectName("RotateLabel")
        self.gridLayout_2.addWidget(self.RotateLabel, 0, 0, 1, 1)
        self.RotateSetting = QtWidgets.QWidget(self.Rotate)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.RotateSetting.sizePolicy().hasHeightForWidth()
        )
        self.RotateSetting.setSizePolicy(sizePolicy)
        self.RotateSetting.setMinimumSize(QtCore.QSize(0, 40))
        self.RotateSetting.setObjectName("RotateSetting")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.RotateSetting)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RotateDegree = QtWidgets.QLineEdit(self.RotateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotateDegree.sizePolicy().hasHeightForWidth())
        self.RotateDegree.setSizePolicy(sizePolicy)
        self.RotateDegree.setMinimumSize(QtCore.QSize(0, 20))
        self.RotateDegree.setObjectName("RotateDegree")
        self.horizontalLayout_3.addWidget(self.RotateDegree)
        self.RotateUnit = QtWidgets.QLabel(self.RotateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotateUnit.sizePolicy().hasHeightForWidth())
        self.RotateUnit.setSizePolicy(sizePolicy)
        self.RotateUnit.setMinimumSize(QtCore.QSize(0, 20))
        self.RotateUnit.setObjectName("RotateUnit")
        self.horizontalLayout_3.addWidget(self.RotateUnit)
        self.gridLayout_2.addWidget(self.RotateSetting, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.Rotate, 0, QtCore.Qt.AlignVCenter)
        self.LocateSetting = QtWidgets.QFrame(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LocateSetting.sizePolicy().hasHeightForWidth()
        )
        self.LocateSetting.setSizePolicy(sizePolicy)
        self.LocateSetting.setMinimumSize(QtCore.QSize(0, 120))
        self.LocateSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LocateSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LocateSetting.setObjectName("LocateSetting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LocateSetting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LocateLabel = QtWidgets.QLabel(self.LocateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocateLabel.sizePolicy().hasHeightForWidth())
        self.LocateLabel.setSizePolicy(sizePolicy)
        self.LocateLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.LocateLabel.setFont(font)
        self.LocateLabel.setObjectName("LocateLabel")
        self.verticalLayout_3.addWidget(self.LocateLabel)
        self.LocatePoints = QtWidgets.QWidget(self.LocateSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocatePoints.sizePolicy().hasHeightForWidth())
        self.LocatePoints.setSizePolicy(sizePolicy)
        self.LocatePoints.setMinimumSize(QtCore.QSize(0, 70))
        self.LocatePoints.setObjectName("LocatePoints")
        self.gridLayout = QtWidgets.QGridLayout(self.LocatePoints)
        self.gridLayout.setObjectName("gridLayout")
        self.OBLeft = QtWidgets.QPushButton(self.LocatePoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBLeft.sizePolicy().hasHeightForWidth())
        self.OBLeft.setSizePolicy(sizePolicy)
        self.OBLeft.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.OBLeft.setFont(font)
        self.OBLeft.setObjectName("OBLeft")
        self.gridLayout.addWidget(self.OBLeft, 0, 0, 1, 1)
        self.OBCenter = QtWidgets.QPushButton(self.LocatePoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBCenter.sizePolicy().hasHeightForWidth())
        self.OBCenter.setSizePolicy(sizePolicy)
        self.OBCenter.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.OBCenter.setFont(font)
        self.OBCenter.setObjectName("OBCenter")
        self.gridLayout.addWidget(self.OBCenter, 2, 0, 1, 1)
        self.OBRight = QtWidgets.QPushButton(self.LocatePoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBRight.sizePolicy().hasHeightForWidth())
        self.OBRight.setSizePolicy(sizePolicy)
        self.OBRight.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.OBRight.setFont(font)
        self.OBRight.setObjectName("OBRight")
        self.gridLayout.addWidget(self.OBRight, 0, 1, 1, 1)
        self.RSPBase = QtWidgets.QPushButton(self.LocatePoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RSPBase.sizePolicy().hasHeightForWidth())
        self.RSPBase.setSizePolicy(sizePolicy)
        self.RSPBase.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.RSPBase.setFont(font)
        self.RSPBase.setObjectName("RSPBase")
        self.gridLayout.addWidget(self.RSPBase, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.LocatePoints)
        self.verticalLayout_2.addWidget(self.LocateSetting, 0, QtCore.Qt.AlignVCenter)
        self.MaskInvisible = QtWidgets.QCheckBox(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.MaskInvisible.sizePolicy().hasHeightForWidth()
        )
        self.MaskInvisible.setSizePolicy(sizePolicy)
        self.MaskInvisible.setMinimumSize(QtCore.QSize(0, 20))
        self.MaskInvisible.setObjectName("MaskInvisible")
        self.verticalLayout_2.addWidget(self.MaskInvisible)
        self.AnalyzeButton = QtWidgets.QPushButton(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalyzeButton.sizePolicy().hasHeightForWidth()
        )
        self.AnalyzeButton.setSizePolicy(sizePolicy)
        self.AnalyzeButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.AnalyzeButton.setFont(font)
        self.AnalyzeButton.setObjectName("AnalyzeButton")
        self.verticalLayout_2.addWidget(self.AnalyzeButton)
        self.MessageBrowser = QtWidgets.QTextBrowser(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.MessageBrowser.sizePolicy().hasHeightForWidth()
        )
        self.MessageBrowser.setSizePolicy(sizePolicy)
        self.MessageBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.MessageBrowser.setObjectName("MessageBrowser")
        self.verticalLayout_2.addWidget(self.MessageBrowser)
        self.AnalyzeProgress = QtWidgets.QProgressBar(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalyzeProgress.sizePolicy().hasHeightForWidth()
        )
        self.AnalyzeProgress.setSizePolicy(sizePolicy)
        self.AnalyzeProgress.setMinimumSize(QtCore.QSize(0, 20))
        self.AnalyzeProgress.setProperty("value", 24)
        self.AnalyzeProgress.setObjectName("AnalyzeProgress")
        self.verticalLayout_2.addWidget(self.AnalyzeProgress)
        self.horizontalLayout.addWidget(self.Setting)
        self.Image = QtWidgets.QFrame(Basic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image.setObjectName("Image")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Image)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RawImage = QtWidgets.QFrame(self.Image)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RawImage.sizePolicy().hasHeightForWidth())
        self.RawImage.setSizePolicy(sizePolicy)
        self.RawImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RawImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RawImage.setObjectName("RawImage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.RawImage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.RawLabel = QtWidgets.QLabel(self.RawImage)
        self.RawLabel.setObjectName("RawLabel")
        self.verticalLayout_5.addWidget(self.RawLabel)
        self.RawImageShow = QtWidgets.QFrame(self.RawImage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RawImageShow.sizePolicy().hasHeightForWidth())
        self.RawImageShow.setSizePolicy(sizePolicy)
        self.RawImageShow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RawImageShow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RawImageShow.setObjectName("RawImageShow")
        self.verticalLayout_5.addWidget(self.RawImageShow)
        self.verticalLayout_4.addWidget(self.RawImage)
        self.AfterPerspectiveImage = QtWidgets.QFrame(self.Image)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AfterPerspectiveImage.sizePolicy().hasHeightForWidth()
        )
        self.AfterPerspectiveImage.setSizePolicy(sizePolicy)
        self.AfterPerspectiveImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AfterPerspectiveImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AfterPerspectiveImage.setObjectName("AfterPerspectiveImage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AfterPerspectiveImage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AfterPerspectiveLabel = QtWidgets.QLabel(self.AfterPerspectiveImage)
        self.AfterPerspectiveLabel.setObjectName("AfterPerspectiveLabel")
        self.verticalLayout_6.addWidget(self.AfterPerspectiveLabel)
        self.AfterPerspectiveImageShow = QtWidgets.QFrame(self.AfterPerspectiveImage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AfterPerspectiveImageShow.sizePolicy().hasHeightForWidth()
        )
        self.AfterPerspectiveImageShow.setSizePolicy(sizePolicy)
        self.AfterPerspectiveImageShow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AfterPerspectiveImageShow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AfterPerspectiveImageShow.setObjectName("AfterPerspectiveImageShow")
        self.verticalLayout_6.addWidget(self.AfterPerspectiveImageShow)
        self.verticalLayout_4.addWidget(self.AfterPerspectiveImage)
        self.horizontalLayout.addWidget(self.Image)

        self.retranslateUi(Basic)
        QtCore.QMetaObject.connectSlotsByName(Basic)

    def retranslateUi(self, Basic):
        _translate = QtCore.QCoreApplication.translate
        Basic.setWindowTitle(_translate("Basic", "Basic"))
        self.LoadDataButton.setText(_translate("Basic", "Load"))
        self.SamplingRateLabel.setText(_translate("Basic", "Sampling Rate"))
        self.SamplingRateUnit.setText(_translate("Basic", "Hz"))
        self.ResetButton.setText(_translate("Basic", "Reset"))
        self.ConfirmButton.setText(_translate("Basic", "Confirm"))
        self.RotateLabel.setText(_translate("Basic", "Rotate"))
        self.RotateUnit.setText(_translate("Basic", "degrees"))
        self.LocateLabel.setText(_translate("Basic", "Locate"))
        self.OBLeft.setText(_translate("Basic", "OB Left"))
        self.OBCenter.setText(_translate("Basic", "OB Center"))
        self.OBRight.setText(_translate("Basic", "OB Right"))
        self.RSPBase.setText(_translate("Basic", "RSP Base"))
        self.MaskInvisible.setText(_translate("Basic", "Mask Invisible"))
        self.AnalyzeButton.setText(_translate("Basic", "Analyze"))
        self.RawLabel.setText(_translate("Basic", "Raw"))
        self.AfterPerspectiveLabel.setText(_translate("Basic", "After Perspective"))


class Ui_Stimulus(object):
    def setupUi(self, Stimulus):
        Stimulus.setObjectName("Stimulus")
        Stimulus.resize(640, 600)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        Stimulus.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Stimulus)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Setting = QtWidgets.QFrame(Stimulus)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Setting.sizePolicy().hasHeightForWidth())
        self.Setting.setSizePolicy(sizePolicy)
        self.Setting.setMinimumSize(QtCore.QSize(200, 0))
        self.Setting.setMaximumSize(QtCore.QSize(280, 16777215))
        self.Setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Setting.setObjectName("Setting")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TotalFrames = QtWidgets.QLabel(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalFrames.sizePolicy().hasHeightForWidth())
        self.TotalFrames.setSizePolicy(sizePolicy)
        self.TotalFrames.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.TotalFrames.setFont(font)
        self.TotalFrames.setObjectName("TotalFrames")
        self.verticalLayout_2.addWidget(self.TotalFrames)
        self.BaselineSetting = QtWidgets.QFrame(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaselineSetting.sizePolicy().hasHeightForWidth()
        )
        self.BaselineSetting.setSizePolicy(sizePolicy)
        self.BaselineSetting.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.BaselineSetting.setFont(font)
        self.BaselineSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BaselineSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BaselineSetting.setObjectName("BaselineSetting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.BaselineSetting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BaselineLabel = QtWidgets.QLabel(self.BaselineSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaselineLabel.sizePolicy().hasHeightForWidth()
        )
        self.BaselineLabel.setSizePolicy(sizePolicy)
        self.BaselineLabel.setMinimumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.BaselineLabel.setFont(font)
        self.BaselineLabel.setObjectName("BaselineLabel")
        self.verticalLayout.addWidget(self.BaselineLabel)
        self.FrameModeButton = QtWidgets.QRadioButton(self.BaselineSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.FrameModeButton.sizePolicy().hasHeightForWidth()
        )
        self.FrameModeButton.setSizePolicy(sizePolicy)
        self.FrameModeButton.setMinimumSize(QtCore.QSize(200, 20))
        self.FrameModeButton.setObjectName("FrameModeButton")
        self.verticalLayout.addWidget(self.FrameModeButton)
        self.FrameModeSetting = QtWidgets.QWidget(self.BaselineSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.FrameModeSetting.sizePolicy().hasHeightForWidth()
        )
        self.FrameModeSetting.setSizePolicy(sizePolicy)
        self.FrameModeSetting.setMinimumSize(QtCore.QSize(0, 40))
        self.FrameModeSetting.setObjectName("FrameModeSetting")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.FrameModeSetting)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BaselineStartLabel = QtWidgets.QLabel(self.FrameModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaselineStartLabel.sizePolicy().hasHeightForWidth()
        )
        self.BaselineStartLabel.setSizePolicy(sizePolicy)
        self.BaselineStartLabel.setMinimumSize(QtCore.QSize(30, 20))
        self.BaselineStartLabel.setObjectName("BaselineStartLabel")
        self.horizontalLayout_5.addWidget(self.BaselineStartLabel)
        self.BaselineStart = QtWidgets.QLineEdit(self.FrameModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaselineStart.sizePolicy().hasHeightForWidth()
        )
        self.BaselineStart.setSizePolicy(sizePolicy)
        self.BaselineStart.setMinimumSize(QtCore.QSize(0, 20))
        self.BaselineStart.setObjectName("BaselineStart")
        self.horizontalLayout_5.addWidget(self.BaselineStart)
        self.BaselineEndLabel = QtWidgets.QLabel(self.FrameModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaselineEndLabel.sizePolicy().hasHeightForWidth()
        )
        self.BaselineEndLabel.setSizePolicy(sizePolicy)
        self.BaselineEndLabel.setMinimumSize(QtCore.QSize(30, 20))
        self.BaselineEndLabel.setObjectName("BaselineEndLabel")
        self.horizontalLayout_5.addWidget(self.BaselineEndLabel)
        self.BaselindEnd = QtWidgets.QLineEdit(self.FrameModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaselindEnd.sizePolicy().hasHeightForWidth())
        self.BaselindEnd.setSizePolicy(sizePolicy)
        self.BaselindEnd.setMinimumSize(QtCore.QSize(0, 20))
        self.BaselindEnd.setObjectName("BaselindEnd")
        self.horizontalLayout_5.addWidget(self.BaselindEnd)
        self.verticalLayout.addWidget(self.FrameModeSetting)
        self.PreStimModeButton = QtWidgets.QRadioButton(self.BaselineSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.PreStimModeButton.sizePolicy().hasHeightForWidth()
        )
        self.PreStimModeButton.setSizePolicy(sizePolicy)
        self.PreStimModeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.PreStimModeButton.setObjectName("PreStimModeButton")
        self.verticalLayout.addWidget(self.PreStimModeButton)
        self.PreStimModeSetting = QtWidgets.QWidget(self.BaselineSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.PreStimModeSetting.sizePolicy().hasHeightForWidth()
        )
        self.PreStimModeSetting.setSizePolicy(sizePolicy)
        self.PreStimModeSetting.setMinimumSize(QtCore.QSize(0, 40))
        self.PreStimModeSetting.setObjectName("PreStimModeSetting")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.PreStimModeSetting)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PreStimSec = QtWidgets.QLineEdit(self.PreStimModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreStimSec.sizePolicy().hasHeightForWidth())
        self.PreStimSec.setSizePolicy(sizePolicy)
        self.PreStimSec.setMinimumSize(QtCore.QSize(0, 20))
        self.PreStimSec.setObjectName("PreStimSec")
        self.horizontalLayout_6.addWidget(self.PreStimSec)
        self.SecondLabel = QtWidgets.QLabel(self.PreStimModeSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SecondLabel.sizePolicy().hasHeightForWidth())
        self.SecondLabel.setSizePolicy(sizePolicy)
        self.SecondLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.SecondLabel.setObjectName("SecondLabel")
        self.horizontalLayout_6.addWidget(self.SecondLabel)
        self.verticalLayout.addWidget(self.PreStimModeSetting)
        self.verticalLayout_2.addWidget(self.BaselineSetting)
        self.Stim = QtWidgets.QFrame(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stim.sizePolicy().hasHeightForWidth())
        self.Stim.setSizePolicy(sizePolicy)
        self.Stim.setMinimumSize(QtCore.QSize(200, 0))
        self.Stim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Stim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Stim.setObjectName("Stim")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Stim)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ListSetting = QtWidgets.QWidget(self.Stim)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListSetting.sizePolicy().hasHeightForWidth())
        self.ListSetting.setSizePolicy(sizePolicy)
        self.ListSetting.setMinimumSize(QtCore.QSize(0, 40))
        self.ListSetting.setObjectName("ListSetting")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ListSetting)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StimLabel = QtWidgets.QLabel(self.ListSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimLabel.sizePolicy().hasHeightForWidth())
        self.StimLabel.setSizePolicy(sizePolicy)
        self.StimLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setBold(True)
        self.StimLabel.setFont(font)
        self.StimLabel.setObjectName("StimLabel")
        self.horizontalLayout_3.addWidget(self.StimLabel)
        self.LoadButton = QtWidgets.QPushButton(self.ListSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadButton.sizePolicy().hasHeightForWidth())
        self.LoadButton.setSizePolicy(sizePolicy)
        self.LoadButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.LoadButton.setFont(font)
        self.LoadButton.setObjectName("LoadButton")
        self.horizontalLayout_3.addWidget(self.LoadButton)
        self.RemoveButton = QtWidgets.QPushButton(self.ListSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveButton.sizePolicy().hasHeightForWidth())
        self.RemoveButton.setSizePolicy(sizePolicy)
        self.RemoveButton.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.RemoveButton.setFont(font)
        self.RemoveButton.setObjectName("RemoveButton")
        self.horizontalLayout_3.addWidget(self.RemoveButton)
        self.verticalLayout_3.addWidget(self.ListSetting)
        self.StimAdd = QtWidgets.QWidget(self.Stim)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimAdd.sizePolicy().hasHeightForWidth())
        self.StimAdd.setSizePolicy(sizePolicy)
        self.StimAdd.setMinimumSize(QtCore.QSize(0, 40))
        self.StimAdd.setObjectName("StimAdd")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.StimAdd)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.StimStartLabel = QtWidgets.QLabel(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.StimStartLabel.sizePolicy().hasHeightForWidth()
        )
        self.StimStartLabel.setSizePolicy(sizePolicy)
        self.StimStartLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.StimStartLabel.setFont(font)
        self.StimStartLabel.setObjectName("StimStartLabel")
        self.horizontalLayout_4.addWidget(self.StimStartLabel)
        self.StimStart = QtWidgets.QLineEdit(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimStart.sizePolicy().hasHeightForWidth())
        self.StimStart.setSizePolicy(sizePolicy)
        self.StimStart.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.StimStart.setFont(font)
        self.StimStart.setObjectName("StimStart")
        self.horizontalLayout_4.addWidget(self.StimStart)
        self.StimEndLabel = QtWidgets.QLabel(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimEndLabel.sizePolicy().hasHeightForWidth())
        self.StimEndLabel.setSizePolicy(sizePolicy)
        self.StimEndLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.StimEndLabel.setFont(font)
        self.StimEndLabel.setObjectName("StimEndLabel")
        self.horizontalLayout_4.addWidget(self.StimEndLabel)
        self.StimEnd = QtWidgets.QLineEdit(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimEnd.sizePolicy().hasHeightForWidth())
        self.StimEnd.setSizePolicy(sizePolicy)
        self.StimEnd.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.StimEnd.setFont(font)
        self.StimEnd.setObjectName("StimEnd")
        self.horizontalLayout_4.addWidget(self.StimEnd)
        self.AddButton = QtWidgets.QPushButton(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setMinimumSize(QtCore.QSize(15, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.AddButton.setFont(font)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout_4.addWidget(self.AddButton)
        self.DeleteButton = QtWidgets.QPushButton(self.StimAdd)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        self.DeleteButton.setMinimumSize(QtCore.QSize(15, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout_4.addWidget(self.DeleteButton)
        self.verticalLayout_3.addWidget(self.StimAdd)
        self.StimulusList = QtWidgets.QListWidget(self.Stim)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StimulusList.sizePolicy().hasHeightForWidth())
        self.StimulusList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.StimulusList.setFont(font)
        self.StimulusList.setObjectName("StimulusList")
        self.verticalLayout_3.addWidget(self.StimulusList)
        self.verticalLayout_2.addWidget(self.Stim)
        self.horizontalLayout.addWidget(self.Setting)
        self.Image = QtWidgets.QFrame(Stimulus)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image.setObjectName("Image")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Image)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MaskedImage = QtWidgets.QFrame(self.Image)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaskedImage.sizePolicy().hasHeightForWidth())
        self.MaskedImage.setSizePolicy(sizePolicy)
        self.MaskedImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MaskedImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MaskedImage.setObjectName("MaskedImage")
        self.verticalLayout_4.addWidget(self.MaskedImage)
        self.ImageSetting = QtWidgets.QWidget(self.Image)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageSetting.sizePolicy().hasHeightForWidth())
        self.ImageSetting.setSizePolicy(sizePolicy)
        self.ImageSetting.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.ImageSetting.setFont(font)
        self.ImageSetting.setObjectName("ImageSetting")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ImageSetting)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RangeLabel = QtWidgets.QLabel(self.ImageSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RangeLabel.sizePolicy().hasHeightForWidth())
        self.RangeLabel.setSizePolicy(sizePolicy)
        self.RangeLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.RangeLabel.setFont(font)
        self.RangeLabel.setObjectName("RangeLabel")
        self.horizontalLayout_2.addWidget(self.RangeLabel)
        self.Percentage = QtWidgets.QLineEdit(self.ImageSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Percentage.sizePolicy().hasHeightForWidth())
        self.Percentage.setSizePolicy(sizePolicy)
        self.Percentage.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.Percentage.setFont(font)
        self.Percentage.setObjectName("Percentage")
        self.horizontalLayout_2.addWidget(self.Percentage)
        self.PercentageLabel = QtWidgets.QLabel(self.ImageSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.PercentageLabel.sizePolicy().hasHeightForWidth()
        )
        self.PercentageLabel.setSizePolicy(sizePolicy)
        self.PercentageLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.PercentageLabel.setObjectName("PercentageLabel")
        self.horizontalLayout_2.addWidget(self.PercentageLabel)
        self.ImageConfirmButton = QtWidgets.QPushButton(self.ImageSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ImageConfirmButton.sizePolicy().hasHeightForWidth()
        )
        self.ImageConfirmButton.setSizePolicy(sizePolicy)
        self.ImageConfirmButton.setMinimumSize(QtCore.QSize(0, 20))
        self.ImageConfirmButton.setObjectName("ImageConfirmButton")
        self.horizontalLayout_2.addWidget(self.ImageConfirmButton)
        self.ImageSaveButton = QtWidgets.QPushButton(self.ImageSetting)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ImageSaveButton.sizePolicy().hasHeightForWidth()
        )
        self.ImageSaveButton.setSizePolicy(sizePolicy)
        self.ImageSaveButton.setMinimumSize(QtCore.QSize(0, 20))
        self.ImageSaveButton.setObjectName("ImageSaveButton")
        self.horizontalLayout_2.addWidget(self.ImageSaveButton)
        self.verticalLayout_4.addWidget(self.ImageSetting)
        self.horizontalLayout.addWidget(self.Image)

        self.retranslateUi(Stimulus)
        QtCore.QMetaObject.connectSlotsByName(Stimulus)

    def retranslateUi(self, Stimulus):
        _translate = QtCore.QCoreApplication.translate
        Stimulus.setWindowTitle(_translate("Stimulus", "Stimulus"))
        self.TotalFrames.setText(_translate("Stimulus", "Total Frames:"))
        self.BaselineLabel.setText(_translate("Stimulus", "Baseline"))
        self.FrameModeButton.setText(_translate("Stimulus", "Frame Mode"))
        self.BaselineStartLabel.setText(_translate("Stimulus", "Start"))
        self.BaselineEndLabel.setText(_translate("Stimulus", "End"))
        self.PreStimModeButton.setText(_translate("Stimulus", "PreStim Mode"))
        self.SecondLabel.setText(_translate("Stimulus", "seconds"))
        self.StimLabel.setText(_translate("Stimulus", "Stimulus"))
        self.LoadButton.setText(_translate("Stimulus", "Load"))
        self.RemoveButton.setText(_translate("Stimulus", "Remove all"))
        self.StimStartLabel.setText(_translate("Stimulus", "Start"))
        self.StimEndLabel.setText(_translate("Stimulus", "End"))
        self.AddButton.setText(_translate("Stimulus", "+"))
        self.DeleteButton.setText(_translate("Stimulus", "-"))
        self.RangeLabel.setText(_translate("Stimulus", "Range"))
        self.PercentageLabel.setText(_translate("Stimulus", "%"))
        self.ImageConfirmButton.setText(_translate("Stimulus", "Confirm"))
        self.ImageSaveButton.setText(_translate("Stimulus", "Save"))
